apiVersion: v1
kind: Service
metadata:
  name: gym-manager-backend
  namespace: gym-manager
spec:
  selector:
    app: gym-manager-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
