services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build: ./backend
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - TOKEN_SECRET_JWT=${TOKEN_SECRET_JWT}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
      - INITIAL_ADMIN_USERNAME=${INITIAL_ADMIN_USERNAME}
      - INITIAL_ADMIN_NAME=${INITIAL_ADMIN_NAME}
    ports:
      - "3000:3000"
    networks:
      - app-network
  mongo:
    image: mongo:latest
    container_name: mongo_gym_manager
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb_data:/data/db
      - ./volumes/mongodb_config:/data/configdb
    networks:
      - app-network
  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express_gym_manager
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-config:
