services:
  frontend:
    build: ./frontend
    container_name: gym_manager_frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build: ./backend
    container_name: gym_manager_backend
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - TOKEN_SECRET_JWT=${TOKEN_SECRET_JWT}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
      - INITIAL_ADMIN_USERNAME=${INITIAL_ADMIN_USERNAME}
      - INITIAL_ADMIN_NAME=${INITIAL_ADMIN_NAME}
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-config:
