services:
  mongo:
    image: mongo:latest
    container_name: mongo_gym
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb_data:/data/db
      - ./volumes/mongodb_config:/data/configdb
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-config:
