services:
  mongo:
    image: mongo:latest
    container_name: mongo_gym_manager
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - back-network
networks:
  back-network:
    driver: bridge
volumes:
  mongo-data: