name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Version Management"]
    branches: [master]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r '.version' ./package.json)" >> $GITHUB_ENV

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gym-manager-frontend:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/gym-manager-frontend:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gym-manager-backend:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/gym-manager-backend:latest
          platforms: linux/amd64,linux/arm64
