name: Setup Branch Protection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Configure branch protection
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'master',
              required_status_checks: {
                strict: true,
                contexts: [
                  'Version Management',
                  'Build and Push Docker Images'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                required_approving_review_count: 1
              },
              restrictions: null
            }); 