name: Version Management

on:
  push:
    branches:
      - master
  workflow_call:
    outputs:
      new_version:
        description: "The new version number"
        value: ${{ jobs.version.outputs.new_version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.release.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install commitlint
        run: bun add -g @commitlint/cli @commitlint/config-conventional

      - name: Validate commit messages
        run: |
          git log --format=%B ${{ github.event.before }}..${{ github.event.after }} | bunx commitlint

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Install semantic-release
        run: bun add -g semantic-release @semantic-release/git

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bunx semantic-release
          echo "new_version=$(jq -r '.version' ./package.json)" >> $GITHUB_OUTPUT 